//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDemo.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        public int Id { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Email { get; set; }
        public Nullable<int> Telefon { get; set; }
        public Nullable<int> TipId { get; set; }
        public bool Aktif { get; set; }
        public string Iller { get; set; }
    
        public virtual KullaniciTip KullaniciTip { get; set; }
    }
}
